# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HiU' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HiU

  target 'HiUTests' do
    
    # Pods for testing
 pod 'SwiftGifOrigin', '~> 1.6.1'
  end

  target 'HiUUITests' do
   
    # Pods for testing
  end

end
